server:
  port: 8080
spring:
  application:
    name: COUND-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sub-kttkpm-14btt-maivuviethungduc/file-config
          default-label: main
        bootstrap: false